from .credentials import *

IS_SERIAL_ENABLED = True
IS_WEB_ENABLED = True
IS_WEB_VIDEO_ENABLED = True
CAMERA_WIDTH = 1920
CAMERA_HEIGHT = 1080
LOG_PATH = 'log'
IMAGE_SAMPLE_FOLDER = ''
DO_SAVE_IMAGE_SAMPLES = False
MNIST_DATABASE_PATH = ''
DATASET_STANDARD_FOLDER = ''
