from .credentials import *

OCR_DO_USE_NCS = True
IS_SERIAL_ENABLED = True
IS_WEB_ENABLED = True
IS_WEB_VIDEO_ENABLED = True
CAMERA_WIDTH = 1920
CAMERA_HEIGHT = 1080
LOG_PATH = 'log'
IMAGE_SAMPLE_FOLDER = ''
IMAGE_TEST_FOLDER = ''
DO_SAVE_IMAGE_SAMPLES = False
DATASET_STANDARD_FOLDER = ''
MNIST_DATABASE_FOLDER = ''
MNIST_MODEL_PATH_PREFIX = ''
MNIST_INFERENCE_PATH_PREFIX = ''
