"""Credentials of this app."""

MAIN_CAMERA_ID = 0
SSL_CERT_FILE = ''
SSL_KEY_FILE = ''
SERVER_PORT = 443
SERVER_ADDRESS = '::'
VIDEO_CAPTURE_FOLDER = ''
SERIAL_PORT = ''
SERIAL_BAUDRATE = 115200
NETWORK_IMAGE_DIMENSIONS = (28, 28)
NETWORK_GRAPH_FILENAME = ''
